<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Zeus" failures="1" tests="5" name="Listener TestCase" time="0.009" errors="0" timestamp="2023-10-16T08:04:12 IST">
  <testcase classname="org.example.Listeners.ListenerTestCase" name="testFour" time="0.0">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="org.example.Listeners.ListenerTestCase" name="testGetDate" time="0.001"/>
  <testcase classname="org.example.Listeners.ListenerTestCase" name="testGetDate" time="0.0"/>
  <testcase classname="org.example.Listeners.ListenerTestCase" name="testOne" time="0.0"/>
  <testcase classname="org.example.Listeners.ListenerTestCase" name="testThree" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at org.example.Listeners.ListenerTestCase.testThree(ListenerTestCase.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- Listener TestCase -->
